name: Deploy

on:
  workflow_run:
    workflows: ['PrepareDependencies']
    types:
      - completed

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - name: Start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/andrewinter/serve
            pm2 start start.sh --name "BringlisteApp"

      - name: Check server status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/andrewinter/serve
            ./status.sh
