name: Deploy

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Prepare files for scp
        run: |
          mkdir -p build
          mv client/ server/ *.js build/

      - name: Remove old build directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: rm -rf /home/andrewinter/serve/build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'build/'
          target: '/home/andrewinter/serve'
